# -*- mode: python ; coding: utf-8 -*-

datas = [
    ('app', 'app'),
    ('static', 'static'),
]

hiddenimports = [
    'pystray',
    'PIL',
    'PIL.Image',
    'PIL.ImageDraw',
    'uvicorn.logging',
    'uvicorn.loops',
    'uvicorn.loops.auto',
    'uvicorn.protocols',
    'uvicorn.protocols.http',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.websockets',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.lifespan',
    'uvicorn.lifespan.on',
    'sqlalchemy.dialects.sqlite',
    'sqlalchemy.sql.default_comparator',
    'jinja2',
    'jinja2.ext',
    'reportlab',
    'reportlab.graphics',
    'reportlab.platypus',
    'reportlab.lib',
    'reportlab.lib.pagesizes',
    'reportlab.lib.styles',
    'reportlab.lib.units',
    'reportlab.lib.enums',
    'reportlab.lib.colors',
    'reportlab.pdfbase',
    'reportlab.pdfbase.pdfmetrics',
    'anyio',
    'anyio._backends._asyncio',
    'starlette',
    'fastapi',
    'schedule',
    'app.main',
    'app.database',
    'app.models',
    'app.models.categoria',
    'app.models.parametro',
    'app.models.abastecedor',
    'app.models.transaccion',
    'app.models.pago_detalle',
    'app.routers.categorias',
    'app.routers.abastecedores',
    'app.routers.transacciones',
    'app.routers.parametros',
    'app.routers.reportes',
    'app.schemas.categoria',
    'app.schemas.abastecedor',
    'app.schemas.transaccion',
    'app.services.cobro_service',
    'app.backup',
]

a = Analysis(
    ['run.py'],
    pathex=['.'],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SistemaAbasto',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False, # Esto evita que se abra la ventana negra de consola
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['logo.ico'], # <--- AGREGÁ ESTA LÍNEA AQUÍ
)